module.exports = {
  ACCOUNT_TYPES: ["Cash", "Credit Cards", "Loan", "Investments", "Property"],
  ACCOUNTS_RECEIVED: "ACCOUNTS_RECEIVED",
  ACCOUNT_RECEIVED: "ACCOUNT_RECEIVED",
  ACCOUNT_RETRIEVED: "ACCOUNT_RETRIEVED",
  ACCOUNT_REMOVED: "ACCOUNT_REMOVED"
};
